name        : libpipeline
version     : 1.4.1
release     : 3
source     :
    - http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.4.1.tar.gz : da46d7b20163aadb9db2faae483f734e9096a7550c84b94029abeab62dd1b9ee
license     :
    - GPL-3.0
summary     : pipeline manipulation library.
description : |
    libpipeline is a C library for manipulating pipelines of subprocesses in a flexible and convenient way.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
