name       : libpipeline
version    : 1.5.2
release    : 6
source     :
    - https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.2.tar.gz : fd59c649c1ae9d67604d1644f116ad4d297eaa66f838e3dfab96b41e85b059fb
license    : GPL-3.0-or-later
component  : system.base
summary    : pipeline manipulation library
description: |
    libpipeline is a C library for manipulating pipelines of subprocesses in a flexible and convenient way.
builddeps  :
    - pkgconfig(check)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

