name       : libpipeline
version    : 1.5.0
release    : 4
source     :
    - https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.0.tar.gz : 0d72e12e4f2afff67fd7b9df0a24d7ba42b5a7c9211ac5b3dcccc5cd8b286f2b
license    : GPL-3.0
summary    : pipeline manipulation library
component  : system.base
description: |
    libpipeline is a C library for manipulating pipelines of subprocesses in a flexible and convenient way.
builddeps  :
    - pkgconfig(check)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

